services:
  ros2:
    image: ros:humble-desktop
    container_name: tinymovr_ros2
    privileged: true
    network_mode: host
    devices:
      - /dev/net/tun
    volumes:
      - ./:/workspace/src/tinymovr_ros
      - /dev:/dev
    working_dir: /workspace
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
